name: Deploy version

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Master
      uses: actions/checkout@master
    - name: Prepare Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Prepare Clojure
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: '1.10.1.708'
    - name: Run unit tests
      run: clojure -A:test:runner
    - name: Check for minimum coverage
      run: clojure -A:test:cloverage
    - name: Update pom.xml
      run: clojure -Spom
    - name: Build
      run: clojure -A:jar
    - name: Zip
      run: zip github-pr-lib.zip github-pr-lib.jar
    - name: Deploy
      run: clojure -A:deploy
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
    - name: Get current version
      run: echo ::set-env name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.version }}
        release_name: v${{ env.version }}
        draft: false
        prerelease: false
    - name: Upload release asset
      id: upload_jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./github-pr-lib.zip
        asset_path: github-pr-lib.zip
        asset_content_type: application/zip
