name: Deploy version

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Master
      uses: actions/checkout@master
    - name: Prepare Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Prepare Clojure
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: '1.10.1.469'
    - name: test
      run: clojure -A:test:runner -M:runner
    - name: Check for minimum coverage
      run: clojure -A:test:cloverage
    - name: pom
      run: clojure -Spom
    - name: build
      run: clojure -A:jar -M:jar
    - name: deploy
      run: clojure -A:deploy -M:deploy
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
