name: Run tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@master
    - name: Prepare Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Prepare Clojure
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: '1.10.1.469'
    - name: Run tests
      run: clojure -A:test:runner -M:runner
    - name: Check for minimum coverage
      run: clojure -A:test:coverage
